import { FormEvent, useRef, useState } from 'react';
import { CalendarDays, Loader2 } from 'lucide-react';
import { ChurchInfo } from '../types';

export default function MeetingRequestForm({ church }: { church: ChurchInfo }) {
  const [form, setForm] = useState({ fullName: '', contact: '', preferredDateTime: '', reason: '' });
  const [status, setStatus] = useState<'idle' | 'sending' | 'success' | 'error'>('idle');
  const submitting = useRef(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (submitting.current) return; submitting.current = true; setStatus('sending'); try { const response = await fetch('/api/meeting-requests', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!response.ok) throw new Error(); setStatus('success'); } catch { setStatus('error'); } finally { submitting.current = false; } };
  if (status === 'success') return <div className="rounded-2xl bg-stone-900 p-7 text-center text-white"><CalendarDays className="mx-auto mb-3 text-[#d4af37]" size={36} /><h3 className="font-serif text-2xl">Your request is with us</h3><p className="mt-2 text-sm text-stone-300">The pastorate team will contact you to confirm a suitable time.</p></div>;
  return <form id="meeting-request" onSubmit={submit} className="rounded-2xl bg-stone-900 p-6 text-white shadow-lg sm:p-8"><h3 className="font-serif text-3xl">Request a meeting</h3><p className="mt-2 text-sm text-stone-300">Send a request to meet with {church.pastorTitle} {church.pastorName}.</p><div className="mt-5 grid gap-4"><Input label="Full name" value={form.fullName} onChange={fullName => setForm({ ...form, fullName })} /><Input label="Email or phone" value={form.contact} onChange={contact => setForm({ ...form, contact })} /><Input label="Preferred date and time" type="datetime-local" value={form.preferredDateTime} onChange={preferredDateTime => setForm({ ...form, preferredDateTime })} /><label className="text-sm">Reason for the meeting<textarea required value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })} rows={3} className="mt-1 w-full rounded-lg border border-stone-600 bg-white/10 px-3 py-2 text-white" /></label></div>{status === 'error' && <p className="mt-3 text-sm text-red-300">We could not send your request. Please try again shortly.</p>}<button disabled={status === 'sending'} className="mt-5 inline-flex w-full justify-center gap-2 rounded-lg bg-[#d4af37] px-4 py-3 text-sm font-bold text-stone-950 hover:bg-[#e6c65b] disabled:opacity-60">{status === 'sending' && <Loader2 size={16} className="animate-spin" />} Send meeting request</button></form>;
}
function Input({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="text-sm">{label}<input required type={type} value={value} onChange={e => onChange(e.target.value)} className="mt-1 w-full rounded-lg border border-stone-600 bg-white/10 px-3 py-2 text-white" /></label>; }
