import { FormEvent, ReactNode, useEffect, useMemo, useRef, useState } from 'react';
import { createClient, Session, SupabaseClient } from '@supabase/supabase-js';
import { Calendar, Check, Church, ClipboardList, KeyRound, Loader2, LogOut, Plus, Trash2, Users } from 'lucide-react';
import { ChurchEvent, ChurchInfo, ConnectCardSubmission, Department, GivingAccount, GivingCategory, MeetingRequest, Testimony } from '../types';
import { ThemeToggle, useTheme } from '../components/ThemeToggle';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
const authClient: SupabaseClient | null = supabaseUrl && supabaseAnonKey ? createClient(supabaseUrl, supabaseAnonKey) : null;

type AdminSection = 'events' | 'departments' | 'testimonies' | 'meetings' | 'church' | 'giving' | 'account';
type EventDraft = Omit<ChurchEvent, 'id'>;
type DepartmentDraft = Omit<Department, 'id'>;
const emptyEvent: EventDraft = { title: '', description: '', date: '', endDate: null, time: '', location: '', category: 'Special', bannerUrl: '' };
const emptyDepartment: DepartmentDraft = { name: '', description: '', howToJoin: '' };

async function adminRequest<T>(session: Session, path: string, options: RequestInit = {}): Promise<T> {
  const response = await fetch(path, { ...options, headers: { Authorization: `Bearer ${session.access_token}`, 'Content-Type': 'application/json', ...options.headers } });
  if (!response.ok) {
    const body = await response.json().catch(() => ({}));
    throw new Error(body.error || 'Request failed');
  }
  return response.status === 204 ? undefined as T : response.json();
}

export default function AdminApp() {
  const { theme, setTheme } = useTheme();
  const [session, setSession] = useState<Session | null>(null);
  const [section, setSection] = useState<AdminSection>('events');
  const [error, setError] = useState('');

  useEffect(() => {
    if (!authClient) return;
    void authClient.auth.getSession().then(({ data }) => setSession(data.session));
    const { data: listener } = authClient.auth.onAuthStateChange((_event, nextSession) => setSession(nextSession));
    return () => listener.subscription.unsubscribe();
  }, []);

  if (!authClient) return <ConfigurationRequired />;
  if (!session) return <Login onError={setError} />;
  return <div className="min-h-screen bg-[#fffdf8] text-stone-900 dark:bg-stone-950 dark:text-stone-100"><header className="border-b border-stone-200 bg-white dark:border-stone-700 dark:bg-stone-900"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4 sm:px-6"><a href="/" className="font-serif text-xl font-bold">RCCG <span className="text-[#a37c19]">Mount Zion</span><span className="ml-2 text-sm font-normal text-stone-500 dark:text-stone-400">Admin</span></a><div className="flex items-center gap-3 text-sm"><span className="hidden text-stone-600 dark:text-stone-300 sm:inline">{session.user.email}</span><ThemeToggle theme={theme} setTheme={setTheme} /><button onClick={() => void authClient.auth.signOut()} className="inline-flex items-center gap-1 rounded-lg border border-stone-300 px-3 py-2 hover:bg-stone-50 dark:border-stone-600 dark:hover:bg-stone-800"><LogOut size={15} /> Sign out</button></div></div></header><main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><p className="eyebrow">Church administration</p><h1 className="font-serif text-4xl">Manage Mount Zion</h1><div className="mt-7 grid gap-6 lg:grid-cols-[220px_1fr]"><nav className="flex gap-2 overflow-x-auto lg:block lg:space-y-2">{([{ key: 'events', label: 'Events', icon: Calendar }, { key: 'departments', label: 'Departments', icon: Users }, { key: 'testimonies', label: 'Testimonies', icon: Check }, { key: 'meetings', label: 'Requests', icon: ClipboardList }, { key: 'giving', label: 'Giving accounts', icon: Plus }, { key: 'church', label: 'Church details', icon: Church }, { key: 'account', label: 'Account', icon: KeyRound }] as const).map(item => <button key={item.key} onClick={() => { setSection(item.key); setError(''); }} className={`inline-flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-sm font-semibold ${section === item.key ? 'bg-stone-900 text-white dark:bg-[#b8942b]' : 'bg-white hover:bg-[#fff7dd] dark:bg-stone-800 dark:hover:bg-stone-700'}`}><item.icon size={16} />{item.label}</button>)}</nav><section>{error && <p className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}{section === 'events' && <EventsPanel session={session} onError={setError} />}{section === 'departments' && <DepartmentsPanel session={session} onError={setError} />}{section === 'testimonies' && <TestimoniesPanel session={session} onError={setError} />}{section === 'meetings' && <RequestsPanel session={session} onError={setError} />}{section === 'giving' && <GivingAccountsPanel session={session} onError={setError} />}{section === 'church' && <ChurchPanel session={session} onError={setError} />}{section === 'account' && <AccountPanel session={session} />}</section></div></main></div>;
}

function ConfigurationRequired() { return <main className="grid min-h-screen place-items-center bg-stone-950 p-6 text-center text-white"><div className="max-w-lg"><h1 className="font-serif text-3xl">Admin setup required</h1><p className="mt-3 text-stone-300">Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to the deployment environment before using the admin login.</p><a href="/" className="mt-6 inline-block rounded-lg bg-[#d4af37] px-4 py-2 font-bold text-stone-950">Return to website</a></div></main>; }

function Login({ onError }: { onError: (message: string) => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); onError(''); const { error } = await authClient!.auth.signInWithPassword({ email, password }); setLoading(false); if (error) onError('We could not sign you in. Check your email and password.'); }
  return <main className="grid min-h-screen place-items-center bg-stone-950 p-4"><form onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white p-7 shadow-2xl"><p className="eyebrow">Restricted area</p><h1 className="mt-2 font-serif text-3xl">Mount Zion admin</h1><p className="mt-2 text-sm text-stone-600">Use an account created by the church administrator. There is no public sign-up.</p><label className="mt-6 block text-sm font-medium">Email<input required type="email" value={email} onChange={event => setEmail(event.target.value)} className="form-input mt-1" /></label><label className="mt-4 block text-sm font-medium">Password<input required type="password" value={password} onChange={event => setPassword(event.target.value)} className="form-input mt-1" /></label><button disabled={loading} className="mt-6 inline-flex w-full justify-center gap-2 rounded-lg bg-[#b8942b] px-4 py-3 font-bold text-white disabled:opacity-60">{loading && <Loader2 className="animate-spin" size={18} />} Sign in</button><a href="/" className="mt-4 block text-center text-sm font-semibold text-[#8a6714]">Return to public website</a></form></main>;
}

function EventsPanel({ session, onError }: PanelProps) {
  const [items, setItems] = useState<ChurchEvent[]>([]); const [draft, setDraft] = useState<EventDraft>(emptyEvent); const [editing, setEditing] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const submitting = useRef(false);
  const load = async () => { try { setLoading(true); setItems(await adminRequest<ChurchEvent[]>(session, '/api/admin/events')); } catch (error) { onError(message(error)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [session]);
  async function submit(event: FormEvent) { event.preventDefault(); if (submitting.current) return; submitting.current = true; setSaving(true); try { if (editing) await adminRequest(session, `/api/admin/events/${editing}`, { method: 'PUT', body: JSON.stringify(draft) }); else await adminRequest(session, '/api/admin/events', { method: 'POST', body: JSON.stringify(draft) }); setDraft(emptyEvent); setEditing(null); await load(); } catch (error) { onError(message(error)); } finally { submitting.current = false; setSaving(false); } }
  return <div><PanelTitle title="Events" description="Add or update public church events. Leave the end date blank for a single-day event." /><form onSubmit={submit} className="admin-card grid gap-3 md:grid-cols-2"><Text label="Title" value={draft.title} onChange={title => setDraft({ ...draft, title })} /><Text label="Start date" type="date" value={draft.date} onChange={date => setDraft({ ...draft, date })} /><Text label="End date (optional)" type="date" value={draft.endDate || ''} onChange={endDate => setDraft({ ...draft, endDate: endDate || null })} /><Text label="Time" value={draft.time} onChange={time => setDraft({ ...draft, time })} /><Text label="Location" value={draft.location} onChange={location => setDraft({ ...draft, location })} /><label className="text-sm font-medium">Category<select value={draft.category} onChange={event => setDraft({ ...draft, category: event.target.value as EventDraft['category'] })} className="form-input mt-1"><option>Special</option><option>Weekly</option><option>Youth</option><option>Women</option><option>Men</option><option>Prayer</option></select></label><Text label="Banner URL (optional)" value={draft.bannerUrl} onChange={bannerUrl => setDraft({ ...draft, bannerUrl })} /><Text label="Description" value={draft.description} onChange={description => setDraft({ ...draft, description })} wide /><div className="flex gap-2 md:col-span-2"><button disabled={saving} className="admin-button disabled:cursor-not-allowed disabled:opacity-60">{saving ? 'Saving…' : editing ? 'Save event' : 'Add event'}</button>{editing && <button type="button" disabled={saving} onClick={() => { setEditing(null); setDraft(emptyEvent); }} className="admin-secondary">Cancel</button>}</div></form><RecordList loading={loading} empty="No events yet.">{items.map(item => <article key={item.id} className="admin-card flex flex-wrap items-start justify-between gap-3"><div><strong>{item.title}</strong><p className="mt-1 text-sm text-stone-600">{item.date}{item.endDate ? ` – ${item.endDate}` : ''} · {item.time} · {item.location}</p></div><div className="flex gap-2"><button onClick={() => { setEditing(item.id); setDraft({ title: item.title, description: item.description, date: item.date, endDate: item.endDate || null, time: item.time, location: item.location, category: item.category, bannerUrl: item.bannerUrl }); }} className="admin-secondary">Edit</button><DeleteButton onDelete={async () => { await adminRequest(session, `/api/admin/events/${item.id}`, { method: 'DELETE' }); await load(); }} onError={onError} /></div></article>)}</RecordList></div>;
}

function DepartmentsPanel({ session, onError }: PanelProps) {
  const [items, setItems] = useState<Department[]>([]); const [draft, setDraft] = useState<DepartmentDraft>(emptyDepartment); const [editing, setEditing] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const submitting = useRef(false);
  const load = async () => { try { setLoading(true); setItems(await adminRequest<Department[]>(session, '/api/admin/departments')); } catch (error) { onError(message(error)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [session]);
  async function submit(event: FormEvent) { event.preventDefault(); if (submitting.current) return; submitting.current = true; setSaving(true); try { if (editing) await adminRequest(session, `/api/admin/departments/${editing}`, { method: 'PUT', body: JSON.stringify(draft) }); else await adminRequest(session, '/api/admin/departments', { method: 'POST', body: JSON.stringify(draft) }); setDraft(emptyDepartment); setEditing(null); await load(); } catch (error) { onError(message(error)); } finally { submitting.current = false; setSaving(false); } }
  return <div><PanelTitle title="Departments" description="Department names, descriptions, and joining information." /><form onSubmit={submit} className="admin-card grid gap-3"><Text label="Department name" value={draft.name} onChange={name => setDraft({ ...draft, name })} /><Text label="Description" value={draft.description} onChange={description => setDraft({ ...draft, description })} area /><Text label="How to get involved" value={draft.howToJoin} onChange={howToJoin => setDraft({ ...draft, howToJoin })} area /><div className="flex gap-2"><button disabled={saving} className="admin-button disabled:cursor-not-allowed disabled:opacity-60">{saving ? 'Saving…' : editing ? 'Save department' : 'Add department'}</button>{editing && <button type="button" disabled={saving} onClick={() => { setEditing(null); setDraft(emptyDepartment); }} className="admin-secondary">Cancel</button>}</div></form><RecordList loading={loading} empty="No departments yet.">{items.map(item => <article key={item.id} className="admin-card flex flex-wrap items-start justify-between gap-3"><div><strong>{item.name}</strong><p className="mt-1 text-sm text-stone-600">{item.description}</p></div><div className="flex gap-2"><button onClick={() => { setEditing(item.id); setDraft({ name: item.name, description: item.description, howToJoin: item.howToJoin }); }} className="admin-secondary">Edit</button><DeleteButton onDelete={async () => { await adminRequest(session, `/api/admin/departments/${item.id}`, { method: 'DELETE' }); await load(); }} onError={onError} /></div></article>)}</RecordList></div>;
}

function TestimoniesPanel({ session, onError }: PanelProps) { const [items, setItems] = useState<Testimony[]>([]); const [loading, setLoading] = useState(true); const load = async () => { try { setLoading(true); setItems(await adminRequest<Testimony[]>(session, '/api/admin/testimonies')); } catch (error) { onError(message(error)); } finally { setLoading(false); } }; useEffect(() => { void load(); }, [session]); const setApproval = async (item: Testimony, isApproved: boolean) => { try { await adminRequest(session, `/api/admin/testimonies/${item.id}`, { method: 'PATCH', body: JSON.stringify({ isApproved }) }); await load(); } catch (error) { onError(message(error)); } }; return <div><PanelTitle title="Testimonies" description="Up to six approved testimonies are public. Approving another automatically returns the oldest approved testimony to review." /><RecordList loading={loading} empty="No testimonies yet.">{items.map(item => <article key={item.id} className="admin-card"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm text-stone-500">{item.authorName} · {item.date}</p><span className={`rounded-full px-2 py-1 text-xs font-bold ${item.isApproved ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800'}`}>{item.isApproved ? 'Public' : 'In review'}</span></div><h3 className="mt-2 font-serif text-xl">{item.title}</h3><p className="mt-2 text-sm leading-6 text-stone-700">{item.content}</p><div className="mt-4 flex gap-2">{item.isApproved ? <button onClick={() => void setApproval(item, false)} className="admin-secondary">Unapprove</button> : <button onClick={() => void setApproval(item, true)} className="admin-button">Approve</button>}<DeleteButton label={item.isApproved ? 'Delete' : 'Reject'} onDelete={async () => { await adminRequest(session, `/api/admin/testimonies/${item.id}`, { method: 'DELETE' }); await load(); }} onError={onError} /></div></article>)}</RecordList></div>; }

type RequestKind = 'connect' | 'meeting';
type SortField = 'submittedAt' | 'fullName';
type SortDirection = 'asc' | 'desc';

function RequestsPanel({ session, onError }: PanelProps) {
  const [kind, setKind] = useState<RequestKind>('connect');
  const [connectCards, setConnectCards] = useState<ConnectCardSubmission[]>([]);
  const [meetings, setMeetings] = useState<MeetingRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState('');
  const [sortField, setSortField] = useState<SortField>('submittedAt');
  const [sortDirection, setSortDirection] = useState<SortDirection>('desc');
  const [selected, setSelected] = useState<{ kind: RequestKind; item: ConnectCardSubmission | MeetingRequest } | null>(null);
  const load = async () => { try { setLoading(true); const [cards, requests] = await Promise.all([adminRequest<ConnectCardSubmission[]>(session, '/api/admin/connect-cards'), adminRequest<MeetingRequest[]>(session, '/api/admin/meeting-requests')]); setConnectCards(cards); setMeetings(requests); } catch (error) { onError(message(error)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [session]);

  const items = kind === 'connect' ? connectCards : meetings;
  const visibleItems = useMemo(() => items.filter(item => item.fullName.toLowerCase().includes(query.trim().toLowerCase())).sort((a, b) => {
    const comparison = sortField === 'fullName' ? a.fullName.localeCompare(b.fullName) : new Date(a.submittedAt).getTime() - new Date(b.submittedAt).getTime();
    return sortDirection === 'asc' ? comparison : -comparison;
  }), [items, query, sortField, sortDirection]);
  const setSort = (field: SortField) => { if (field === sortField) setSortDirection(direction => direction === 'asc' ? 'desc' : 'asc'); else { setSortField(field); setSortDirection(field === 'submittedAt' ? 'desc' : 'asc'); } };
  const sortLabel = (field: SortField, text: string) => <button type="button" onClick={() => setSort(field)} className="font-semibold hover:text-[#8a6714]">{text}{sortField === field ? sortDirection === 'asc' ? ' ↑' : ' ↓' : ''}</button>;

  return <div><PanelTitle title="Requests" description="Private visitor connections and meeting requests for signed-in administrators." /><div className="admin-card"><div className="flex flex-wrap items-center justify-between gap-3"><div className="inline-flex rounded-lg border border-stone-300 p-1 dark:border-stone-600"><button onClick={() => setKind('connect')} className={`rounded-md px-3 py-2 text-sm font-bold ${kind === 'connect' ? 'bg-[#b8942b] text-white' : 'text-stone-600 dark:text-stone-300'}`}>Connect Cards</button><button onClick={() => setKind('meeting')} className={`rounded-md px-3 py-2 text-sm font-bold ${kind === 'meeting' ? 'bg-[#b8942b] text-white' : 'text-stone-600 dark:text-stone-300'}`}>Meeting Requests</button></div><input aria-label="Search requests by name" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search by name…" className="form-input w-full sm:w-64" /></div></div><RecordList loading={loading} empty={query ? 'No requests match that name.' : kind === 'connect' ? 'No connect cards yet.' : 'No meeting requests yet.'}><div className="overflow-x-auto rounded-xl border border-stone-200 bg-white dark:border-stone-700 dark:bg-stone-900"><table className="min-w-full text-left text-sm"><thead className="border-b border-stone-200 bg-[#fff7dd] text-stone-700 dark:border-stone-700 dark:bg-stone-800 dark:text-stone-200"><tr><th className="px-4 py-3">{sortLabel('fullName', 'Name')}</th>{kind === 'connect' ? <><th className="px-4 py-3">Email</th><th className="px-4 py-3">Phone</th><th className="px-4 py-3">First time?</th><th className="px-4 py-3">Prayer request</th></> : <><th className="px-4 py-3">Contact</th><th className="px-4 py-3">Preferred time</th><th className="px-4 py-3">Reason</th></>}<th className="px-4 py-3 whitespace-nowrap">{sortLabel('submittedAt', 'Submitted')}</th><th className="px-4 py-3">Actions</th></tr></thead><tbody className="divide-y divide-stone-200 dark:divide-stone-700">{visibleItems.map(item => kind === 'connect' ? <ConnectCardRow key={item.id} item={item as ConnectCardSubmission} onOpen={() => setSelected({ kind, item: item as ConnectCardSubmission })} onDelete={async () => { await adminRequest(session, `/api/admin/connect-cards/${item.id}`, { method: 'DELETE' }); setSelected(current => current?.item.id === item.id ? null : current); await load(); }} onError={onError} /> : <MeetingRequestRow key={item.id} item={item as MeetingRequest} onOpen={() => setSelected({ kind, item: item as MeetingRequest })} onDelete={async () => { await adminRequest(session, `/api/admin/meeting-requests/${item.id}`, { method: 'DELETE' }); setSelected(current => current?.item.id === item.id ? null : current); await load(); }} onError={onError} />)}</tbody></table></div></RecordList>{selected && <RequestDetailDialog kind={selected.kind} item={selected.item} onClose={() => setSelected(null)} />}</div>;
}

function ConnectCardRow({ item, onOpen, onDelete, onError }: { item: ConnectCardSubmission; onOpen: () => void; onDelete: () => Promise<void>; onError: (message: string) => void }) { return <tr className="align-top"><td className="px-4 py-3 font-semibold"><button type="button" onClick={onOpen} className="text-left hover:text-[#8a6714] hover:underline">{item.fullName}</button></td><td className="px-4 py-3">{item.email}</td><td className="px-4 py-3">{item.phone}</td><td className="px-4 py-3">{item.isFirstTime ? 'Yes' : 'No'}</td><td className="max-w-xs px-4 py-3 text-stone-600 dark:text-stone-300">View full details</td><td className="whitespace-nowrap px-4 py-3 text-stone-500">{new Date(item.submittedAt).toLocaleString()}</td><td className="px-4 py-3"><DeleteButton label="Delete" onDelete={onDelete} onError={onError} /></td></tr>; }
function MeetingRequestRow({ item, onOpen, onDelete, onError }: { item: MeetingRequest; onOpen: () => void; onDelete: () => Promise<void>; onError: (message: string) => void }) { return <tr className="align-top"><td className="px-4 py-3 font-semibold"><button type="button" onClick={onOpen} className="text-left hover:text-[#8a6714] hover:underline">{item.fullName}</button></td><td className="px-4 py-3">{item.contact}</td><td className="px-4 py-3">{item.preferredDateTime}</td><td className="max-w-xs px-4 py-3 text-stone-600 dark:text-stone-300">View full details</td><td className="whitespace-nowrap px-4 py-3 text-stone-500">{new Date(item.submittedAt).toLocaleString()}</td><td className="px-4 py-3"><DeleteButton label="Delete" onDelete={onDelete} onError={onError} /></td></tr>; }
function RequestDetailDialog({ kind, item, onClose }: { kind: RequestKind; item: ConnectCardSubmission | MeetingRequest; onClose: () => void }) { const fields: Array<[string, string]> = kind === 'connect' ? [['Full name', item.fullName], ['Email', (item as ConnectCardSubmission).email], ['Phone', (item as ConnectCardSubmission).phone], ['First time visitor', (item as ConnectCardSubmission).isFirstTime ? 'Yes' : 'No'], ['Prayer request', (item as ConnectCardSubmission).prayerRequest || 'None provided'], ['Submitted', new Date(item.submittedAt).toLocaleString()]] : [['Full name', item.fullName], ['Contact', (item as MeetingRequest).contact], ['Preferred date and time', (item as MeetingRequest).preferredDateTime], ['Reason for meeting', (item as MeetingRequest).reason], ['Submitted', new Date(item.submittedAt).toLocaleString()]]; return <div role="dialog" aria-modal="true" aria-labelledby="request-detail-title" className="fixed inset-0 z-50 grid place-items-center bg-stone-950/60 p-4" onMouseDown={onClose}><div className="max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl dark:bg-stone-900" onMouseDown={event => event.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">{kind === 'connect' ? 'Connect Card' : 'Meeting Request'}</p><h3 id="request-detail-title" className="mt-1 font-serif text-2xl">{item.fullName}</h3></div><button type="button" onClick={onClose} className="admin-secondary">Close</button></div><dl className="mt-6 space-y-4">{fields.map(([name, value]) => <div key={name}><dt className="text-xs font-bold uppercase tracking-wide text-stone-500 dark:text-stone-400">{name}</dt><dd className="mt-1 whitespace-pre-wrap break-words text-sm leading-6 text-stone-800 dark:text-stone-100">{value}</dd></div>)}</dl></div></div>; }

const givingCategories: GivingCategory[] = ['Tithe', 'Offering', 'Thanksgiving', 'Building Fund', 'Missions', 'Other'];
const emptyGivingAccount: Omit<GivingAccount, 'id'> = { category: 'Tithe', bankName: '', accountName: '', accountNumber: '' };

function AccountPanel({ session }: { session: Session }) {
  const [email, setEmail] = useState(session.user.email || '');
  const [password, setPassword] = useState('');
  const [emailStatus, setEmailStatus] = useState('');
  const [passwordStatus, setPasswordStatus] = useState('');
  const [savingEmail, setSavingEmail] = useState(false);
  const [savingPassword, setSavingPassword] = useState(false);

  async function changeEmail(event: FormEvent) {
    event.preventDefault();
    setSavingEmail(true); setEmailStatus('');
    // Without an explicit redirect, Supabase builds the confirmation link from
    // the project's Site URL, which defaults to localhost — so a link mailed
    // from the deployed site sends the administrator to a page on their own
    // machine. Sending the live origin keeps the link on whichever host the
    // change was requested from. The origin must also be listed under
    // Authentication → URL Configuration → Redirect URLs, or Supabase falls
    // back to the Site URL again.
    const { error } = await authClient!.auth.updateUser(
      { email: email.trim() },
      { emailRedirectTo: `${window.location.origin}/admin` },
    );
    setSavingEmail(false);
    setEmailStatus(error ? `Email change failed — ${error.message}` : 'Confirmation link sent. Supabase may email both the old and the new address — open the link in each to complete the change.');
  }

  async function changePassword(event: FormEvent) {
    event.preventDefault();
    if (password.length < 6) { setPasswordStatus('Password must be at least 6 characters.'); return; }
    setSavingPassword(true); setPasswordStatus('');
    const { error } = await authClient!.auth.updateUser({ password });
    setSavingPassword(false);
    if (error) { setPasswordStatus(`Password change failed — ${error.message}`); return; }
    setPassword(''); setPasswordStatus('Password updated successfully.');
  }

  return <div><PanelTitle title="Account" description="Update the shared administrator email address or password." /><div className="grid gap-5 lg:grid-cols-2"><form onSubmit={changeEmail} className="admin-card"><h3 className="font-serif text-2xl">Change email</h3><p className="mt-1 text-sm text-stone-600 dark:text-stone-300">Supabase will send a confirmation link to the new address.</p><label className="mt-5 block text-sm font-medium">New email<input required type="email" value={email} onChange={event => setEmail(event.target.value)} className="form-input mt-1" /></label><button disabled={savingEmail} className="admin-button mt-4 disabled:opacity-60">{savingEmail ? 'Sending…' : 'Send confirmation link'}</button>{emailStatus && <p className={`mt-3 text-sm font-semibold ${emailStatus.includes('failed') ? 'text-red-700 dark:text-red-300' : 'text-emerald-700 dark:text-emerald-300'}`}>{emailStatus}</p>}</form><form onSubmit={changePassword} className="admin-card"><h3 className="font-serif text-2xl">Change password</h3><p className="mt-1 text-sm text-stone-600 dark:text-stone-300">Use at least 6 characters.</p><label className="mt-5 block text-sm font-medium">New password<input required minLength={6} type="password" value={password} onChange={event => setPassword(event.target.value)} className="form-input mt-1" /></label><button disabled={savingPassword} className="admin-button mt-4 disabled:opacity-60">{savingPassword ? 'Updating…' : 'Update password'}</button>{passwordStatus && <p className={`mt-3 text-sm font-semibold ${passwordStatus.includes('failed') || passwordStatus.includes('must be') ? 'text-red-700 dark:text-red-300' : 'text-emerald-700 dark:text-emerald-300'}`}>{passwordStatus}</p>}</form></div></div>;
}

function GivingAccountsPanel({ session, onError }: PanelProps) {
  const [accounts, setAccounts] = useState<GivingAccount[]>([]); const [draft, setDraft] = useState<Omit<GivingAccount, 'id'>>(emptyGivingAccount); const [editing, setEditing] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = async () => { try { setLoading(true); setAccounts(await adminRequest<GivingAccount[]>(session, '/api/admin/giving-accounts')); } catch (error) { onError(message(error)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [session]);
  const openNew = () => { const next = givingCategories.find(category => !accounts.some(account => account.category === category)); if (!next) return; setEditing(null); setDraft({ ...emptyGivingAccount, category: next }); };
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); try { if (editing) await adminRequest(session, `/api/admin/giving-accounts/${editing}`, { method: 'PUT', body: JSON.stringify(draft) }); else await adminRequest(session, '/api/admin/giving-accounts', { method: 'POST', body: JSON.stringify(draft) }); await load(); openNew(); } catch (error) { onError(message(error)); } finally { setSaving(false); } }
  return <div><PanelTitle title="Giving accounts" description="Create one bank account for each giving purpose. Select a category to edit its details." /><div className="mb-5 flex flex-wrap gap-3">{accounts.map(account => <button type="button" key={account.id} onClick={() => { setEditing(account.id); setDraft({ category: account.category, bankName: account.bankName, accountName: account.accountName, accountNumber: account.accountNumber }); }} className={`rounded-xl border px-4 py-3 text-left font-semibold ${editing === account.id ? 'border-[#b8942b] bg-[#fff7dd] text-[#6f5110] dark:bg-stone-800 dark:text-[#f2d267]' : 'border-stone-200 bg-white hover:bg-[#fff7dd] dark:border-stone-700 dark:bg-stone-800 dark:hover:bg-stone-700'}`}>{account.category}</button>)}{accounts.length < givingCategories.length && <button type="button" onClick={openNew} className="admin-secondary inline-flex items-center gap-1"><Plus size={16} /> Add new account</button>}</div>{loading ? <Loading /> : <form onSubmit={submit} className="admin-card grid gap-3 md:grid-cols-2"><label className="text-sm font-medium">Purpose<select disabled={Boolean(editing)} value={draft.category} onChange={event => setDraft({ ...draft, category: event.target.value as GivingCategory })} className="form-input mt-1 disabled:opacity-60">{givingCategories.map(category => <option disabled={!editing && accounts.some(account => account.category === category)} key={category}>{category}</option>)}</select></label><Text label="Bank name" value={draft.bankName} onChange={bankName => setDraft({ ...draft, bankName })} /><Text label="Account name" value={draft.accountName} onChange={accountName => setDraft({ ...draft, accountName })} /><Text label="Account number" value={draft.accountNumber} onChange={accountNumber => setDraft({ ...draft, accountNumber })} /><div className="flex flex-wrap gap-2 md:col-span-2"><button disabled={saving} className="admin-button disabled:opacity-60">{saving ? 'Saving…' : editing ? 'Save account' : 'Add account'}</button>{editing && <><button type="button" onClick={openNew} className="admin-secondary">Add another account</button><DeleteButton label="Delete account" onError={onError} onDelete={async () => { await adminRequest(session, `/api/admin/giving-accounts/${editing}`, { method: 'DELETE' }); await load(); openNew(); }} /></>}</div></form>}</div>;
}

function ChurchPanel({ session, onError }: PanelProps) {
  const [church, setChurch] = useState<ChurchInfo | null>(null);
  const [serviceTimes, setServiceTimes] = useState(''); const [initial, setInitial] = useState('');
  const [loading, setLoading] = useState(true); const [savingLiveStatus, setSavingLiveStatus] = useState(false);
  const [saveStatus, setSaveStatus] = useState('');
  const normalize = (data: ChurchInfo) => ({ ...data, isLiveNow: data.isLiveNow ?? false, liveStreamUrl: data.liveStreamUrl ?? null });
  useEffect(() => { void (async () => { try { const normalized = normalize(await adminRequest<ChurchInfo>(session, '/api/admin/church-info')); setChurch(normalized); setServiceTimes(JSON.stringify(normalized.serviceTimes, null, 2)); setInitial(JSON.stringify(normalized)); } catch (error) { onError(message(error)); } finally { setLoading(false); } })(); }, [session]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!church) return; try { const parsed = JSON.parse(serviceTimes); if (!Array.isArray(parsed)) throw new Error('Service times must be a JSON list.'); const payload = { ...church, serviceTimes: parsed }; if (JSON.stringify(payload) === initial) { setSaveStatus('No changes to save'); return; } const normalized = normalize(await adminRequest<ChurchInfo>(session, '/api/admin/church-info', { method: 'PATCH', body: JSON.stringify(payload) })); setChurch(normalized); setServiceTimes(JSON.stringify(normalized.serviceTimes, null, 2)); setInitial(JSON.stringify(normalized)); setSaveStatus('Saved'); } catch (error) { const reason = message(error); setSaveStatus(`Save failed — ${reason}`); onError(reason); } }
  async function toggleLiveStatus() { if (!church) return; setSavingLiveStatus(true); try { const normalized = normalize(await adminRequest<ChurchInfo>(session, '/api/admin/church-info', { method: 'PATCH', body: JSON.stringify({ ...church, isLiveNow: !church.isLiveNow }) })); setChurch(normalized); setInitial(JSON.stringify(normalized)); } catch (error) { onError(message(error)); } finally { setSavingLiveStatus(false); } }
  if (loading) return <Loading />; if (!church) return null;
  const fields: Array<Exclude<keyof ChurchInfo, 'id' | 'serviceTimes' | 'isLiveNow' | 'liveStreamUrl'>> = ['name', 'tagline', 'pastorName', 'pastorTitle', 'address', 'city', 'state', 'phone', 'email', 'facebook_url', 'liveStreamEmbedId', 'accentColor', 'logoText'];
  return <div><PanelTitle title="Church details" description="Changes appear on the public site after saving." /><div className={`mb-5 rounded-xl border p-5 ${church.isLiveNow ? 'border-emerald-300 bg-emerald-50 dark:border-emerald-800 dark:bg-emerald-950/30' : 'border-stone-200 bg-white dark:border-stone-700 dark:bg-stone-900'}`}><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-serif text-xl">Service live status</p><p className="mt-1 text-sm text-stone-600 dark:text-stone-300"><span className={`mr-2 inline-block h-2.5 w-2.5 rounded-full ${church.isLiveNow ? 'bg-emerald-500' : 'bg-stone-400'}`} />{church.isLiveNow ? 'Visitors can see that the service is live.' : 'Visitors currently see the service as offline.'}</p></div><button type="button" disabled={savingLiveStatus} onClick={() => void toggleLiveStatus()} className={church.isLiveNow ? 'rounded-lg bg-red-700 px-5 py-3 font-bold text-white hover:bg-red-800 disabled:opacity-60' : 'rounded-lg bg-emerald-700 px-5 py-3 font-bold text-white hover:bg-emerald-800 disabled:opacity-60'}>{savingLiveStatus ? 'Updating…' : church.isLiveNow ? 'End Live' : 'Go Live'}</button></div><label className="mt-4 block text-sm font-medium">Live video URL <span className="font-normal text-stone-600 dark:text-stone-300">(paste Facebook’s share link before going live)</span><input type="url" value={church.liveStreamUrl || ''} onChange={event => { setChurch({ ...church, liveStreamUrl: event.target.value || null }); setSaveStatus(''); }} placeholder="https://www.facebook.com/..." className="form-input mt-1" /></label></div><form onSubmit={submit} className="admin-card grid gap-3 md:grid-cols-2">{fields.map(field => <Text key={field} label={label(field)} value={String(church[field])} onChange={value => { setChurch({ ...church, [field]: value }); setSaveStatus(''); }} wide={field === 'tagline'} />)}<Text label="Service times (JSON)" value={serviceTimes} onChange={value => { setServiceTimes(value); setSaveStatus(''); }} area wide /><div className="md:col-span-2"><button className="admin-button">Save church details</button>{saveStatus && <p className={`mt-2 text-sm font-semibold ${saveStatus.startsWith('Save failed') ? 'text-red-700 dark:text-red-300' : 'text-emerald-700 dark:text-emerald-300'}`}>{saveStatus}</p>}</div></form></div>;
}

type PanelProps = { session: Session; onError: (message: string) => void };
function PanelTitle({ title, description }: { title: string; description: string }) { return <div className="mb-5"><h2 className="font-serif text-3xl">{title}</h2><p className="mt-1 text-sm text-stone-600">{description}</p></div>; }
function Text({ label, value, onChange, type = 'text', area = false, wide = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; area?: boolean; wide?: boolean }) { return <label className={`text-sm font-medium ${wide ? 'md:col-span-2' : ''}`}>{label}{area ? <textarea required value={value} onChange={event => onChange(event.target.value)} rows={4} className="form-input mt-1" /> : <input required type={type} value={value} onChange={event => onChange(event.target.value)} className="form-input mt-1" />}</label>; }
function RecordList({ loading, empty, children }: { loading: boolean; empty: string; children: ReactNode }) { const list = useMemo(() => children, [children]); return <div className="mt-6 space-y-3">{loading ? <Loading /> : (Array.isArray(list) && list.length === 0 ? <p className="rounded-lg bg-white p-4 text-sm text-stone-600">{empty}</p> : list)}</div>; }
function Loading() { return <p className="rounded-lg bg-white p-4 text-sm text-stone-600">Loading…</p>; }
function DeleteButton({ onDelete, onError, label = 'Delete' }: { onDelete: () => Promise<void>; onError: (message: string) => void; label?: string }) { return <button onClick={async () => { if (!window.confirm(`Are you sure you want to ${label.toLowerCase()} this item?`)) return; try { await onDelete(); } catch (error) { onError(message(error)); } }} className="inline-flex items-center gap-1 rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-700 hover:bg-red-50"><Trash2 size={14} />{label}</button>; }
function message(error: unknown) { return error instanceof Error ? error.message : 'Something went wrong. Please try again.'; }
function label(field: string) { return field.replace(/([A-Z])/g, ' $1').replace(/^./, value => value.toUpperCase()).replace('Url', 'URL'); }
