import { FormEvent, useEffect, useRef, useState } from 'react';
import { Calendar, ChevronDown, Clock, Heart, MapPin, Menu, Play, X } from 'lucide-react';
import { ChurchEvent, ChurchInfo, Department, GivingAccount, Testimony } from './types';
import ConnectCard from './components/ConnectCard';
import EventsCalendar from './components/EventsCalendar';
import GivingModal from './components/GivingModal';
import MeetingRequestForm from './components/MeetingRequestForm';
import { ThemeToggle, useTheme } from './components/ThemeToggle';
import { trackEvent } from './analytics';

type MenuKey = 'about' | 'connect' | 'events' | null;
type EventsView = 'calendar' | 'list';
const nav = { about: [['Departments', '#departments'], ['Testimonies', '#testimonies']], connect: [['Connect card', '#connect-card-section'], ['Prayer request', '#connect-card-section'], ['Baptism', '#connect-card-section'], ['Meeting request', '#meeting-request']], events: [['Events', '#events']] } as const;
const dateRange = (event: ChurchEvent) => event.endDate ? `${event.date} – ${event.endDate}` : event.date;

export default function App() {
  const { theme, setTheme } = useTheme();
  const [church, setChurch] = useState<ChurchInfo | null>(null); const [events, setEvents] = useState<ChurchEvent[]>([]); const [departments, setDepartments] = useState<Department[]>([]); const [testimonies, setTestimonies] = useState<Testimony[]>([]); const [givingAccounts, setGivingAccounts] = useState<GivingAccount[]>([]);
  const [openMenu, setOpenMenu] = useState<MenuKey>(null); const [mobileOpen, setMobileOpen] = useState(false); const [givingOpen, setGivingOpen] = useState(false); const [expanded, setExpanded] = useState<string | null>(null); const [testimonyOpen, setTestimonyOpen] = useState(false); const [testimonySending, setTestimonySending] = useState(false); const testimonySubmitting = useRef(false); const [eventsView, setEventsView] = useState<EventsView>('calendar'); const [notice, setNotice] = useState('');
  useEffect(() => { void loadChurchInfo(); const timer = window.setInterval(() => { void refreshChurchInfo(); }, 45_000); return () => window.clearInterval(timer); }, []);
  async function loadChurchInfo() { try { const response = await fetch('/api/church-info'); if (!response.ok) throw new Error(); const data: ChurchInfo = await response.json(); setChurch({ ...data, isLiveNow: data.isLiveNow ?? false }); await Promise.all([loadContent(), loadDepartments(), loadGivingAccounts()]); } catch { setNotice('We are unable to load church information right now. Please refresh shortly.'); } }
  async function refreshChurchInfo() { try { const response = await fetch('/api/church-info'); if (response.ok) setChurch(await response.json()); } catch { /* Keep the last successful church data visible. */ } }
  async function loadContent() { try { const [eventResponse, testimonyResponse] = await Promise.all([fetch('/api/events'), fetch('/api/testimonies')]); if (eventResponse.ok) setEvents(await eventResponse.json()); if (testimonyResponse.ok) setTestimonies(await testimonyResponse.json()); } catch { setNotice('Some content could not be loaded.'); } }
  async function loadDepartments() { try { const response = await fetch('/api/departments'); if (response.ok) setDepartments(await response.json()); } catch { setNotice('Department information could not be loaded.'); } }
  async function loadGivingAccounts() { try { const response = await fetch('/api/giving-accounts'); if (response.ok) setGivingAccounts(await response.json()); } catch { setNotice('Giving details could not be loaded.'); } }
  async function submitTestimony(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (testimonySubmitting.current) return; testimonySubmitting.current = true; setTestimonySending(true); const form = new FormData(event.currentTarget); try { const response = await fetch('/api/testimonies', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ authorName: form.get('authorName'), title: form.get('title'), content: form.get('content') }) }); if (!response.ok) throw new Error(); trackEvent('testimony_submitted'); setTestimonyOpen(false); setNotice('Thank you. Your testimony has been received and will be reviewed before it appears publicly.'); } catch { setNotice('We could not submit your testimony. Please try again shortly.'); } finally { testimonySubmitting.current = false; setTestimonySending(false); } }
  function openGiving() { trackEvent('give_button_clicked'); setGivingOpen(true); }
  if (!church) return <main className="grid min-h-screen place-items-center bg-stone-950 p-6 text-center text-white"><p>{notice || 'Loading RCCG Mount Zion…'}</p></main>;
  return <div className="min-h-screen bg-[#fffdf8] text-stone-900 dark:bg-stone-950 dark:text-stone-100"><header className="sticky top-0 z-40 border-b border-stone-200 bg-white/95 backdrop-blur dark:border-stone-700 dark:bg-stone-900/95"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-3 sm:px-6"><a href="#home" className="font-serif text-xl font-bold">RCCG <span className="text-[#a37c19]">Mount Zion</span></a><nav className="hidden items-center gap-2 md:flex"><a href="#home" className="nav-link dark:text-stone-200">Home</a>{Object.keys(nav).map(key => <div key={key} className="relative"><button onClick={() => setOpenMenu(openMenu === key ? null : key as MenuKey)} className="nav-link inline-flex items-center gap-1 capitalize dark:text-stone-200">{key}<ChevronDown size={14} /></button>{openMenu === key && <div className="absolute left-0 mt-2 w-44 rounded-lg border border-stone-200 bg-white p-2 shadow-lg dark:border-stone-700 dark:bg-stone-800">{nav[key as keyof typeof nav].map(([label, href]) => <a onClick={() => setOpenMenu(null)} key={label} href={href} className="block rounded px-3 py-2 text-sm hover:bg-[#fff7dd] dark:hover:bg-stone-700">{label}</a>)}</div>}</div>)}<ThemeToggle theme={theme} setTheme={setTheme} /><button onClick={openGiving} className="rounded-full bg-[#8a6714] px-4 py-2 text-sm font-bold text-white hover:bg-[#6f5110]">Give</button></nav><div className="flex items-center gap-2 md:hidden"><ThemeToggle theme={theme} setTheme={setTheme} /><button onClick={() => setMobileOpen(!mobileOpen)} aria-label="Toggle navigation">{mobileOpen ? <X /> : <Menu />}</button></div></div>{mobileOpen && <nav className="border-t border-stone-200 px-4 py-3 dark:border-stone-700 md:hidden"><a href="#home" className="mobile-link dark:text-stone-200">Home</a>{Object.entries(nav).flatMap(([key, items]) => items.map(([label, href]) => <a key={label} href={href} onClick={() => setMobileOpen(false)} className="mobile-link dark:text-stone-200">{key}: {label}</a>))}<button onClick={openGiving} className="mobile-link text-left text-[#8a6714] dark:text-[#f2d267]">Give</button></nav>}</header>
    {notice && <div className="bg-[#fff1cc] px-4 py-3 text-center text-sm text-stone-800 dark:bg-[#493916] dark:text-stone-100">{notice}</div>}
    <main><section id="home" className="hero-image relative isolate overflow-hidden"><div className="absolute inset-0 -z-10 bg-stone-950/70" /><div className="mx-auto grid min-h-[580px] max-w-7xl content-center px-4 py-20 sm:px-6"><div className="max-w-2xl text-white"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#f2d267]">Redeemed Christian Church of God</p><h1 className="mt-4 font-serif text-5xl leading-tight sm:text-7xl">{church.name}</h1><p className="mt-5 max-w-xl text-lg text-white/85">{church.tagline}</p><div className="mt-8 flex flex-wrap items-center gap-3"><a href="#connect-card-section" className="rounded-full bg-[#d4af37] px-6 py-3 font-bold text-stone-950 hover:bg-[#e4c457]">Plan your visit</a>{church.facebook_url && <a onClick={() => trackEvent('facebook_live_button_clicked')} href={church.isLiveNow && church.liveStreamUrl ? church.liveStreamUrl : church.facebook_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-white/60 px-6 py-3 font-bold hover:bg-white/10"><Play size={16} /> Watch us on Facebook</a>}<span className="inline-flex items-center gap-2 text-sm font-bold"><span className={`h-2.5 w-2.5 rounded-full ${church.isLiveNow ? 'bg-emerald-400 shadow-[0_0_10px_#4ade80]' : 'bg-stone-400'}`} aria-hidden="true" />{church.isLiveNow ? 'Live now' : 'Offline'}</span></div></div></div></section>
      <section id="about" className="mx-auto grid max-w-7xl gap-8 px-4 py-16 sm:px-6 lg:grid-cols-[1.1fr_.9fr]"><div><p className="eyebrow">Join us</p><h2 className="section-title">A place to worship, grow and belong</h2><p className="mt-4 max-w-2xl leading-7 text-stone-600 dark:text-stone-300">We gather at St Oran’s College in Lower Hutt and welcome people of every age and background. Meet {church.pastorTitle} {church.pastorName} and the Mount Zion family.</p></div><div className="rounded-2xl border border-[#d4af37]/40 bg-[#fff9e8] p-6 dark:bg-stone-900"><h3 className="font-serif text-2xl">Service times</h3><div className="mt-4 space-y-3">{church.serviceTimes.map(service => <div key={`${service.day}-${service.name}`} className="flex gap-3"><Clock className="mt-0.5 text-[#a37c19]" size={18} /><p><strong>{service.day}, {service.time}</strong><br /><span className="text-sm text-stone-600 dark:text-stone-300">{service.name}</span></p></div>)}</div></div></section>
      <section id="departments" className="bg-stone-950 px-4 py-16 text-white sm:px-6"><div className="mx-auto max-w-5xl"><p className="eyebrow text-[#f2d267]">Ministries</p><h2 className="section-title text-white">Find your place to serve</h2><div className="mt-8 space-y-3">{departments.length ? departments.map(department => <article key={department.id} className="rounded-xl border border-white/15 bg-white/5"><button onClick={() => setExpanded(expanded === department.id ? null : department.id)} className="flex w-full items-center justify-between p-5 text-left"><span><strong className="text-lg">{department.name}</strong><span className="mt-1 block text-sm text-stone-300">{department.description}</span></span><ChevronDown className={expanded === department.id ? 'rotate-180 text-[#d4af37]' : ''} /></button>{expanded === department.id && <div className="border-t border-white/10 px-5 py-4 text-sm leading-6 text-stone-200"><strong className="text-[#f2d267]">How to get involved</strong><p className="mt-1">{department.howToJoin}</p></div>}</article>) : <p className="mt-6 text-stone-300">Ministry information will be shared here soon.</p>}</div></div></section>
      <section id="connect-card-section" className="mx-auto grid max-w-7xl gap-8 px-4 py-16 sm:px-6 lg:grid-cols-2"><ConnectCard onSuccessSubmit={() => { trackEvent('connect_card_submitted'); setNotice('Thank you for connecting with us.'); }} /><MeetingRequestForm church={church} /></section>
      <section id="events" className="bg-[#fff7e6] px-4 py-16 dark:bg-stone-900 sm:px-6"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">What’s on</p><h2 className="section-title">Events</h2></div><div className="inline-flex rounded-lg border border-stone-300 p-1 dark:border-stone-600"><button onClick={() => setEventsView('calendar')} className={`rounded-md px-3 py-2 text-sm font-bold ${eventsView === 'calendar' ? 'bg-[#8a6714] text-white' : 'text-stone-600 dark:text-stone-300'}`}>Calendar</button><button onClick={() => setEventsView('list')} className={`rounded-md px-3 py-2 text-sm font-bold ${eventsView === 'list' ? 'bg-[#8a6714] text-white' : 'text-stone-600 dark:text-stone-300'}`}>List</button></div></div>{eventsView === 'calendar' ? <EventsCalendar events={events} /> : <div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{events.length ? events.map(item => <article key={item.id} className="rounded-xl bg-white p-5 shadow-sm dark:bg-stone-800"><Calendar className="text-[#a37c19]" /><p className="mt-4 text-sm font-bold text-[#a37c19]">{dateRange(item)} · {item.time}</p><h3 className="mt-1 font-serif text-2xl">{item.title}</h3><p className="mt-2 text-sm text-stone-600 dark:text-stone-300">{item.description}</p><p className="mt-3 text-sm"><MapPin className="mr-1 inline" size={14} />{item.location}</p></article>) : <p className="text-stone-600 dark:text-stone-300">Upcoming events will be announced here.</p>}</div>}</div></section>
      <section id="testimonies" className="mx-auto max-w-7xl px-4 py-16 sm:px-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Good news</p><h2 className="section-title">Testimonies</h2></div><button onClick={() => setTestimonyOpen(true)} className="rounded-full border border-[#b8942b] px-5 py-2 text-sm font-bold text-[#8a6714] hover:bg-[#fff7dd] dark:text-[#f2d267] dark:hover:bg-stone-800">Share your testimony</button></div><div className="mt-8 grid gap-5 md:grid-cols-3">{testimonies.length ? testimonies.map(testimony => <article key={testimony.id} className="rounded-xl border border-stone-200 p-5 dark:border-stone-700"><Heart className="text-[#b8942b]" size={20} /><h3 className="mt-4 font-serif text-xl">{testimony.title}</h3><p className="mt-2 text-sm leading-6 text-stone-600 dark:text-stone-300">{testimony.content}</p><p className="mt-4 text-xs font-bold text-stone-500 dark:text-stone-400">{testimony.authorName}</p></article>) : <p className="text-stone-600 dark:text-stone-300">No testimonies are displayed yet.</p>}</div></section>
      <section id="contact" className="bg-stone-900 px-4 py-16 text-white sm:px-6"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2"><div><p className="eyebrow text-[#f2d267]">Visit Mount Zion</p><h2 className="section-title text-white">Find us in Lower Hutt</h2><p className="mt-4 text-stone-300">St Oran’s College, {church.address}, {church.city}, {church.state}</p><p className="mt-2 text-sm text-stone-400">41.2117° S, 174.9009° E</p><a className="mt-5 inline-flex gap-2 font-bold text-[#f2d267]" target="_blank" rel="noreferrer" href="https://www.google.com/maps/search/?api=1&query=St+Orans+College+550+High+Street+Lower+Hutt">Open in Google Maps <MapPin size={17} /></a></div><div className="rounded-2xl border border-white/15 bg-white/5 p-6"><h3 className="font-serif text-2xl">Contact</h3><div className="mt-3 space-y-2 text-stone-200"><p>Phone: {church.phone}</p><p>Email: {church.email}</p>{church.facebook_url && <p>Facebook: <a href={church.facebook_url} target="_blank" rel="noreferrer" className="font-semibold text-[#f2d267] hover:underline">Visit our Facebook page</a></p>}</div></div></div></section></main>
    <footer className="bg-stone-950 px-4 py-8 text-center text-sm text-stone-400">RCCG Mount Zion © 2026</footer>{testimonyOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-stone-950/60 p-4"><form onSubmit={submitTestimony} className="w-full max-w-lg rounded-2xl bg-white p-6 dark:bg-stone-900"><div className="flex justify-between"><h2 className="font-serif text-2xl dark:text-white">Share your testimony</h2><button type="button" disabled={testimonySending} onClick={() => setTestimonyOpen(false)} className="dark:text-white"><X /></button></div><p className="mt-2 text-sm text-stone-600 dark:text-stone-300">Testimonies are reviewed before appearing publicly.</p><input required name="authorName" placeholder="Your name" className="form-input mt-5 dark:border-stone-600 dark:bg-stone-800 dark:text-white" /><input required name="title" placeholder="Testimony title" className="form-input mt-3 dark:border-stone-600 dark:bg-stone-800 dark:text-white" /><textarea required name="content" rows={5} placeholder="What would you like to share?" className="form-input mt-3 dark:border-stone-600 dark:bg-stone-800 dark:text-white" /><button disabled={testimonySending} className="mt-4 w-full rounded-lg bg-[#8a6714] py-3 font-bold text-white disabled:cursor-not-allowed disabled:opacity-60">{testimonySending ? 'Submitting…' : 'Submit for review'}</button></form></div>}<GivingModal isOpen={givingOpen} onClose={() => setGivingOpen(false)} accounts={givingAccounts} /></div>;
}
